
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Inventory_Management_System.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Accounts
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Accounts()
    {

        this.Cart = new HashSet<Cart>();

        this.HistoryTransaction = new HashSet<HistoryTransaction>();

    }


    public int user_ID { get; set; }

    public string user_name { get; set; }

    public string user_password { get; set; }

    public string user_Address { get; set; }

    public string user_firstname { get; set; }

    public string user_lastname { get; set; }

    public string user_email { get; set; }

    public string user_phone { get; set; }

    public string user_position { get; set; }

    public Nullable<int> roleID { get; set; }

    public string user_gender { get; set; }

    public Nullable<System.DateTime> user_birthdate { get; set; }

    public string user_Status { get; set; }



    public virtual Role Role { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Cart> Cart { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HistoryTransaction> HistoryTransaction { get; set; }

}

}
