
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Inventory_Management_System.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vw_BestSeller
{

    public int ID { get; set; }

    public string Products { get; set; }

    public Nullable<int> Number_of_orders { get; set; }

    public Nullable<int> Total_quantity { get; set; }

    public Nullable<decimal> Total { get; set; }

}

}
