
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Inventory_Management_System.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vw_HistoryTransaction
{

    public int ID { get; set; }

    public int Order_no { get; set; }

    public string Clerk { get; set; }

    public string Products { get; set; }

    public string Category { get; set; }

    public string Quantity { get; set; }

    public Nullable<decimal> Total { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string Customer { get; set; }

    public string Address { get; set; }

}

}
