
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Inventory_Management_System.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vw_SelectProducts
{

    public int ID { get; set; }

    public string Product_Name { get; set; }

    public string SKU { get; set; }

    public string Quantity { get; set; }

    public Nullable<decimal> Price { get; set; }

    public string Description { get; set; }

}

}
